name: 180 Deploy android library

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  deploy:
    # runs-on: macos-14
    runs-on: ubuntu-latest
    # runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v4

      # https://github.com/actions/setup-java
      - uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version-file: '.java-version'

      # https://github.com/gradle/actions
      - uses: gradle/actions/setup-gradle@v3
        with:
          gradle-home-cache-cleanup: true

      - name: Check version
        run: |
          tag=$(jshell .github/scripts/get-version-name.jsh)
          bash .github/scripts/can-release.bash $tag
        env:
          GH_TOKEN: ${{ github.token }}

      - run: chmod +x gradlew

      - name: Publish to GitHub Packages
        env:
          USERNAME: ${{ github.repository_owner }}
          TOKEN: ${{ github.token }}
        run: ./gradlew trykmmlib:publishAndroidReleasePublicationToGitHubPackagesRepository --info
