name: 181a Upload podspec

on:
  workflow_call:
    secrets:
      PRIVATE_KEY:
        required: true

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-181a
  cancel-in-progress: true

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v4

      # https://github.com/actions/create-github-app-token
      - name: Create token for dist repository
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: "TryKMMRepoPod"

      # https://github.com/ruby/setup-ruby
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Set up development
        run: make setup-ios

      # https://github.com/tshion/apply-git-user
      - uses: tshion/apply-git-user@2.0.0
        with:
          global: true
          user: github-actions

      - name: Set up cocoapod repo
        run: bundle exec pod repo add TryKMMRepoPod https://tshion:${{ steps.app-token.outputs.token }}@github.com/tshion/TryKMMRepoPod.git

      - name: Upload podspec
        run: bundle exec pod repo push TryKMMRepoPod TryKMMLib.podspec --allow-warnings
