name: 999 Show macOS version

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  show:
    runs-on: macos-14
    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v4

      - run: xcodebuild -version
