name: Deploy android library

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/create-github-app-token
      - name: Create token for maven repository
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: "TryKMMRepoMaven"

      # https://github.com/actions/checkout
      - name: Checkout maven repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/TryKMMRepoMaven
          path: repo-maven
          token: ${{ steps.app-token.outputs.token }}

      # https://github.com/actions/checkout
      - uses: actions/checkout@v4

      # https://github.com/actions/setup-java
      - name: set up JDK
        uses: actions/setup-java@v4
        with:
          java-version-file: '.java-version'
          distribution: 'microsoft'
          cache: gradle

      - name: Build aar
        run: |
          chmod +x gradlew
          ./gradlew trykmmlib:publishAndroidReleasePublicationToMavenRepository

      - uses: tshion/apply-git-user@2.0.0
        with:
          path: repo-maven
          user: github-actions

      - name: Push aar to maven repository
        working-directory: repo-maven
        run: |
          git add *
          git commit --message "Deploy libraries"
          git push origin
