name: Deploy ios library

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13
    steps:
        # https://github.com/actions/checkout
        - uses: actions/checkout@v4

        # https://github.com/actions/setup-java
        - name: set up JDK
          uses: actions/setup-java@v4
          with:
            java-version-file: '.java-version'
            distribution: 'microsoft'
            cache: gradle

        - name: Grant execute permission for gradlew
          run: chmod +x gradlew

        - name: Build xcframework
          run: ./gradlew trykmmlib:assembleTryKMMLibReleaseXCFramework

        # https://github.com/actions/upload-artifact
        - uses: actions/upload-artifact@v4
          with:
            name: trykmmlib-ios
            path: trykmmlib/build/XCFrameworks/release/*.xcframework


  transfer:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/create-github-app-token
      - name: Create token for dist repository
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: "TryKMMRepo"

      # https://github.com/actions/checkout
      - name: Checkout dist repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/TryKMMRepo
          path: repo
          token: ${{ steps.app-token.outputs.token }}

      # https://github.com/actions/download-artifact
      - uses: actions/download-artifact@v4
        with:
          name: trykmmlib-ios
          path: tmp

      - name: Replace libraries at dist repository
        run: |
          rm -rf ./repo/*.xcframework
          mv -f ./tmp/*.xcframework ./repo

      - name: Setup git settings
        uses: tshion/apply-git-user@2.0.0
        with:
          path: repo
          user: github-actions

      - name: Git push
        working-directory: repo
        run: |
          git add --all *.xcframework/*
          git commit --message "Deploy libraries"
          git push origin
