name: Deploy android library

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v4

      # https://github.com/actions/setup-java
      - name: set up JDK
        uses: actions/setup-java@v4
        with:
          java-version-file: '.java-version'
          distribution: 'microsoft'
          cache: gradle

      - name: Publish to GitHub Packages
        env:
          USERNAME: ${{ github.repository_owner }}
          TOKEN: ${{ github.token }}
        run: |
          chmod +x gradlew
          ./gradlew trykmmlib:publishAndroidReleasePublicationToGitHubPackagesRepository
